services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    user: "${PROMETHEUS_UID:-65534}:${PROMETHEUS_GID:-65534}"
    restart: unless-stopped
    network_mode: "service:tailscale-prometheus"
    env_file:
      - .env
    volumes:
      - ./data:/prometheus:rw
      - ./config/prometheus.yml:/prom-config/prometheus.yml:ro
      - ./config/rules:/prom-config/rules:ro
      - ./config/prometheus-entrypoint.sh:/prom-config/entrypoint.sh:ro
      - ./config/file-sd:/tmp/prometheus-file-sd:rw
    entrypoint: ["/bin/sh", "/prom-config/entrypoint.sh"]
    command:
      - --config.file=/prom-config/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${GRAFANA_UID:-472}:${GRAFANA_GID:-472}"
    restart: unless-stopped
    network_mode: "service:tailscale-grafana"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SERVER_PROTOCOL=${GRAFANA_SERVER_PROTOCOL:-http}
      - GF_SERVER_DOMAIN=${GRAFANA_SERVER_DOMAIN:-grafana}
      - GF_SERVER_ROOT_URL=${GRAFANA_SERVER_ROOT_URL:-%(protocol)://%(domain)/}
    volumes:
      - ./data/grafana:/var/lib/grafana:rw
      - ./config/grafana/provisioning:/etc/grafana/provisioning:ro
  tailscale-prometheus:
    image: tailscale/tailscale:stable
    hostname: prometheus
    environment:
      - TS_SERVE_CONFIG=/config/prometheus.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-prometheus/state:/var/lib/tailscale
      - ./tailscale-prometheus/config:/config
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  tailscale-grafana:
    image: tailscale/tailscale:stable
    hostname: grafana
    environment:
      - TS_SERVE_CONFIG=/config/grafana.json
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - ./tailscale-grafana/state:/var/lib/tailscale
      - ./tailscale-grafana/config:/config
      - /dev/net/tun:/dev/net/tun
    env_file:
      - .env
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
