global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /prom-config/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'netdata'
    metrics_path: /api/v1/allmetrics
    params:
      format: ['prometheus']
    file_sd_configs:
      - files:
          - /tmp/prometheus-file-sd/netdata.json
  - job_name: 'coder'
    scrape_interval: 15s
    scheme: https
    metrics_path: /prometheus
    tls_config:
      insecure_skip_verify: true
    file_sd_configs:
      - files:
          - /tmp/prometheus-file-sd/coder.json
